# Generated by Django 5.2.5 on 2025-10-21 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_propanetank_is_active_reservation_is_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 23, 22, 3, 23, 683732, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='owner_photo',
            field=models.ImageField(default='default.jpg', help_text='Upload your photo', upload_to='store_owners/'),
        ),
    ]
