# Generated by Django 5.2.5 on 2025-11-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_reservation_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='payment_proof_uploaded_at',
            new_name='pickup_proof_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='payment_proof',
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_proof',
            field=models.ImageField(blank=True, null=True, upload_to='pickup_proofs/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Pickup'), ('pending_approval', 'Pending Admin Approval'), ('approved', 'Approved - Completed'), ('rejected', 'Pickup Proof Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
